package com.example.buildsrc

object Dependencies {
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val firebaseMessaging = "com.google.firebase:firebase-messaging-ktx:${Versions.firebaseMessaging}"
    const val workRuntime = "androidx.work:work-runtime-ktx:${Versions.workRuntime}"
    const val materialDesign = "com.google.android.material:material:${Versions.material}"
    const val junit = "junit:junit:${Versions.jUnit}"
    const val androidTestImpl = "androidx.test.ext:junit:${Versions.junitAndroid}"
    const val espresso = "androidx.test.espresso:espresso-core:${Versions.espresso}"
    const val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navigationFragment}"
    const val navigation = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    const val hiltAndroid = "com.google.dagger:hilt-android:${Versions.hiltAndroid}"
    const val hiltCompiler = "com.google.dagger:hilt-compiler:${Versions.hiltCompiler}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val converterGson = "com.squareup.retrofit2:converter-gson:${Versions.retrofitGson}"
    const val picasso = "com.squareup.picasso:picasso:${Versions.picasso}"
    const val multidex = "com.android.support:multidex:${Versions.multidex}"
    const val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val loginInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.loginInterceptor}"
    const val firebaseAnalytics = "com.google.firebase:firebase-analytics-ktx:${Versions.firebaseAnalytics}"
    const val mockito = "org.mockito.kotlin:mockito-kotlin:${Versions.mockito}"
    const val kotlinxCoroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.kotlinxCoroutinesTest}"
    const val kotlinxCoroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.kotlinxCoroutinesCore}"
    const val mockk = "io.mockk:mockk:${Versions.mockk}"
    const val coreTesting = "androidx.arch.core:core-testing:${Versions.coreTesting}"
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
}