package com.example.buildsrc

object Versions {
    const val gradlePlugin = "4.2.1"
    const val kotlin = "1.5.0"
    const val timber = "4.7.1"
    const val appCompat = "1.6.1"
    const val material = "1.8.0"
    const val constraintLayout = "2.1.4"
    const val jUnit = "4.13.2"
    const val firebaseMessaging = "23.1.2"
    const val workRuntime = "2.8.1"
    const val junitAndroid = "1.1.5"
    const val espresso = "3.5.1"
    const val navigationFragment = "2.5.3"
    const val navigation = "2.5.3"
    const val hiltAndroid = "2.45"
    const val hiltCompiler = "2.45"
    const val retrofit = "2.9.0"
    const val retrofitGson = "2.9.0"
    const val picasso = "2.71828"
    const val multidex = "2.0.1"
    const val coroutines = "1.6.4"
    const val okhttp = "4.9.2"
    const val loginInterceptor = "4.9.2"
    const val firebaseAnalytics = "21.3.0"
    const val mockito = "4.1.0"
    const val kotlinxCoroutinesTest = "1.6.4"
    const val kotlinxCoroutinesCore = "1.3.8"
    const val mockk = "1.10.2"
    const val coreTesting = "2.2.0"
    const val coreKtx = "1.10.1"
}